aliases: []
creation_timestamp: 1743703243304
current_stage: None
description: null
last_updated_timestamp: 1743703243304
name: sentiment_analysis_pipeline
run_id: f0ef55e5b797476faa5d58b8240bf47e
run_link: null
source: file:///content/Practica/mlflow/292130715233975858/f0ef55e5b797476faa5d58b8240bf47e/artifacts/sentiment_analysis
status: READY
status_message: null
storage_location: file:///content/Practica/mlflow/292130715233975858/f0ef55e5b797476faa5d58b8240bf47e/artifacts/sentiment_analysis
user_id: null
version: 4
